#!/usr/bin/env bash
# Code Developed By: Rushyang Darji
# Initial Build: 29.03.2011
# Last Updated: 02.04.2011
# Prerequisites: zenity, JDK, libnotify-bin. 
# I created this script when I was working on servlets & I found myself very lazy to go into terminal and compile everytime.
# ~/.source4servlet file contains the commands to export the environment variable for JAVA_HOME, JRE_HOME & CLASSPATH

source "/home/rushyang/.source4servlet"
temp=$(mktemp)
trap "rm $temp" 0 1 2
for uri in $NAUTILUS_SCRIPT_SELECTED_URIS; do
	base=`basename "$uri"`
	javac "$base" 2> $temp | zenity --progress --pulsate --auto-close --text="Compiling..." --title="$base" --width=250 --height=125 | sleep 1
	[[ -s "$temp" ]] && zenity --text-info --filename="$temp" --title="Error log for $base" --width=600 --height=600
done
