#!/usr/bin/env bash
# Code Developed By: Rushyang Darji
# Initial Build: 20.04.2011
# Prerequisites: zenity, JDK, libnotify-bin. 
# This is the updated file after my first script 'Compile java File(s)'. 
# I wrote this because, again I felt very lazy to make classes directory right beside the 'src'. (I wish I could make src from thought in my mind too!)
# ~/.source4servlet file contains the commands to export the environment variable for JAVA_HOME, JRE_HOME & CLASSPATH

#[[ -z "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" ]] && zenity --error --text="No Files were selected! Script will now exit." --no-wrap && exit
src=`echo $NAUTILUS_SCRIPT_CURRENT_URI | cut -d'/' -f3- | sed 's/%20/ /g'`
#zenity --info --text="$src" --no-wrap
servlet="`dirname "$src"`"
#zenity --info --text="$servlet" --no-wrap
#webinf="`basename "$webinfc"`"
#zenity --info --text="$webinf" --no-wrap
flag=0
webinf=""
for check in "$servlet"/*; do
	base="`basename "$check"`"
	if [[ "$base" = "WEB-INF" ]]; then
		flag=1
		webinf="$check"
		#zenity --info --text="WEB-INF found at: $webinf" --no-wrap
		break
	fi
done
#zenity --info --text="Outside for, webinf value: $webinf" --no-wrap
if [[ "$flag" -eq "0" ]]; then
	zenity --error --text="Current Working directory isn't beside WEB-INF. Script can't be continued." --no-wrap
	exit
fi
temp2=$(mktemp)
temp=$(mktemp)
temp3=$(mktemp)
trap "rm $temp $temp2 $temp3; exit" 0 1 2
source "/home/rushyang/.source4servlet"
for i in "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS"; do
	echo "$i" | sed -n 's/\/home/\n\/home/gp' > $temp2
done
#	i=`cat $temp2 | awk NF | head -n1`
awk NF $temp2 > $temp3
#zenity --text-info --filename="$temp2"
#zenity --text-info --filename="$temp3"
classes=$webinf/'classes'
#[[ -d "$classes" ]] && zenity --info --text="$classes already exists" --no-wrap
[[ ! -d "$classes" ]] && mkdir "$classes" 2> $temp
while read -r uri; do
#zenity --info --text="$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS"
#for uri in "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS"; do
	base=`basename "$uri"`
	#zenity --info --text="I'm about to compile this file: $base"
	javac -d "$classes" "$base" 2> $temp | zenity --progress --pulsate --auto-close --text="Compiling..." --title="$base" --width=250 --height=125 | sleep 1
	[[ -s "$temp" ]] && zenity --text-info --filename="$temp" --title="Error log for $base" --width=600 --height=600
done < "$temp3"
