#!/usr/bin/env bash
# This script will make all file persmission 755

temp=$(mktemp)
trap "rm $temp; exit" 1 2 
chmod 755 * 2>"$temp"
SIZE=`ls -s "$temp" | awk '{print $1}'`
ls -l >> "$temp"
[[ "$SIZE" -ne "0" ]] && zenity --text-info --filename="$temp" --title="Error log for task 755" --timeout=20 --width=600 --height=600
