#!/usr/bin/env bash
#From Rushyang Darji
# For removing multiple prefix pattern
# This is due to most stupid OS: "Windows" of course. Windows does not allow spaces at the end of directory or filename. When such directories/files are created through linux, windows just can't access them. 
# This script will remove last sapce (if exists) from file/directoy present into current directory.
#pword=`zenity --entry --text='Enter the exact word(s) of a file of beginning:' --entry-text='Link to ' --height=150 --width=400 --title="Remove matching prefix pattern"`

pword=' '
for i in *
do
		lword=${i: -1:1}
		if [[ "$lword" = " " ]]; then
			fn=${i%"$pword"}
			zenity --info --text="Renaming to...\"$fn\""
			mv "$i" "$fn"
		fi

done
